version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "wrale/devops"

  # Maintain dependencies for Helm charts
  - package-ecosystem: "docker"
    directory: "/charts"
    schedule:
      interval: "daily"
    reviewers:
      - "wrale/chart-maintainers"
    ignore:
      # Ignore patch updates for now, focus on minor and major
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "wrale/maintainers"
