apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "app-template.selectorLabels" . | nindent 4 }}
    {{- with .Values.service.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
